### PR TITLE
Working version of lb-ng

### PR DESCRIPTION
**Pull request by ap-ware**
This branch contains a working version of the lb-ng script file used when creating a new service file from update_model in checkit-backend.

### CODE REVIEW

**Comment by cookejames** [comment]
Can we not install this via npm?

**Comment by galp** [comment]
looks good to me
James Cooke said :
> Can we not install this via npm?
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/elektron-technology/checkit-ng-lb-services/pull/1#issuecomment-268980328

-- 
|
|'`'.           .''.            ..
|    '	      .'    '.        .`  '.
|-----`.----.'------- '------------.  
|       '..'           `.    '
|                        `..'   
|
http://ag.kiben.net

**Comment by cookejames** [comment]
Hello Antonios! Hope you're well and recovered from running the length of Greece!

**Comment by cookejames** [comment]
This change probably belongs in the backend repository not the public checkit-ng-lb-services. Closing it here. We need to look at making this work with the current version and failing that pull in this dependency via npm.

**Pull request closed without merging**
